language: python
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_254fbb7fb5b5_key -iv $encrypted_254fbb7fb5b5_iv
  -in deploy_key.enc -out ~\/.ssh/deploy_key -d
- openssl aes-256-cbc -K $encrypted_125cbe95f7e7_key -iv $encrypted_125cbe95f7e7_iv
  -in deploy_key.enc -out ~\/.ssh/deploy_key -d
- sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
- sudo apt-get update -qq
- sudo apt-get install -y -o Dpkg::Options::="--force-confold" --force-yes docker-engine
install:
- pip install git+https://github.com/ansible/ansible-container.git
- pip install ansible
script:
- git clone git@github.com:masschallenge/impact-api.git
