language: python
sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_f3fe491c7ba5_key -iv $encrypted_f3fe491c7ba5_iv -in deploy_key.enc -out ~\/.ssh/id_impact_deploy_key -d
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confold" --force-yes docker-engine

install:
  # Install the latest Ansible Container and Ansible
  - pip install git+https://github.com/ansible/ansible-container.git
  - pip install ansible
script:
  - git clone git@github.com:masschallenge/impact-api.git
